### ISSUE TITLE
Working with RequireJS

### ISSUE THREAD

**Issue by ricksuggs** [zertosh/jquery-audit#3]
When using a dependency manager and async javascript resource loader such as requirejs, it looks like the plugin is not able to initialize. Getting this in the "jQuery Audit" tab:

Error: "@(window.jQuery is missing)

![image](https://f.cloud.github.com/assets/739730/1812372/5ef81388-6e78-11e3-922a-65bc319ac9b8.png)

**Comment by zertosh** [comment]
Hi. The extension checks every time you change nodes to see if there is a `jQuery` function on `window`. So, if jQuery is loaded async, you have to click to another node and then click back to force a reload. But this might not be your problem. Although jQuery 1.10.1 registers itself as an AMD module, it still creates a `jQuery` function on `window` unless you explicitly call `jQuery.noConflict();`. Maybe that's what's going on. In a day or two, I'll push out an update checks for an AMD module, and hopefully that'll resolve your issue.

**Comment by ricksuggs** [comment]
Great. Changing nodes worked! thanks

**Comment by zertosh** [comment]
Glad it worked out.
