### ISSUE TITLE
jump to the line where handler is defined

### ISSUE THREAD

**Issue by jmcbee** [zertosh/jquery-audit#7]
Hi, is it possible to jump to the line where the handler is defined?

![](https://lh5.googleusercontent.com/-znjmUe58_BY/VDyfi1-t_ZI/AAAAAAAABkI/4ERB4GfWEz4/s0/2014-10-14_11-58-56.png)

**Comment by zertosh** [comment]
Yes, follow the "Show Function Definition" instructions https://github.com/zertosh/jquery-audit#live-dom-nodes-functions-and-objects

**Comment by jmcbee** [comment]
Shit, sorry for not rtfrf.
