### ISSUE TITLE
Chrome extension question

### ISSUE THREAD

**Issue by Dimosthenis** [zertosh/jquery-audit#8]
Hello.
I'm trying to use jquery audit extension but the console tab of jquery audit in chrome is always blank even when I target elements that respond to javascript events.

I could not find anything referring to similar issues so here I am. What am I doing wrong?
Another thing is that even though helpers are "on" from the options, I've never seen the 
<--@(window)--> or <--@(document)--> in the inspection console..

I'd really like to use this extension since I've heard so many good words.
Thank you!

**Comment by zertosh** [comment]
Can you post a screenshot of what you see?

**Comment by Dimosthenis** [comment]
https://www.dropbox.com/s/rfpmven8bmklg3s/Audit-Capture.JPG?dl=0

**Comment by Dimosthenis** [comment]
I've checked it from a mac and windows on chrome with same google account and I get the same blank console.
Thank you in advance zertosh

**Comment by zertosh** [comment]
Works for me. I wonder if you have another extension that's causing it to fail. Try turning all your extensions off. It could also be your Chrome, if it's really old. I just tried it on Chrome 42.0.2311.152 OS X.

![vbpoa](https://cloud.githubusercontent.com/assets/830952/7612539/802ed484-f959-11e4-95d8-2d4d2df60dfc.png)

**Comment by Dimosthenis** [comment]
unfortunately even when I disable all other extension and update chrome I still get the same thing.
I guess I'll have to wait jq audit update and see..  :[

**Comment by zertosh** [comment]
That's really weird. I can't think of any other reason why it wouldn't work. The extension has been pretty stable for over a year. I don't see any updates in the near future (unless jQuery changes it's events store), especially ones to address a bug I can't even repro.

**Comment by Dimosthenis** [comment]
You think it has something to do with node being installed in both computers?
I also find it very strange

**Comment by zertosh** [comment]
Nope. It's got to be something with your Chrome install.
